
networks:
  hadoopnet:
    driver: bridge

services:

  headnode:
    image: remstef/hadoop3-jobimtext
    hostname: headnode
    command: >-
      /bin/bash -c "
        ssh-server & 
        sleep 1 && hdfs namenode & 
        sleep 1 && yarn resourcemanager &
        sleep 1 && mapred historyserver & 
        wait
      "
    volumes:
      # pass authorized_keys for quicker login
      - ~/.ssh/id_ed25519.pub:/opt/hadoop/.ssh/authorized_keys:ro
    networks:
      hadoopnet:
        aliases: 
          - namenode
          - resourcemanager
          - historyserver
    ports:
      - 9870:9870
      - 8088:8088
      - 2222:22
    env_file:
      - ./config-h3.env
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"

  node01: &workerref
    image: remstef/hadoop3
    hostname: node01
    command: >-
      /bin/bash -c "
        hdfs datanode & sleep 1 &&
        yarn nodemanager & wait
      "
    networks:
      hadoopnet:
        aliases: 
          - datanode
          - nodemanager
    env_file:
      - ./config-h3.env
    environment:
      - SLEEP_SECONDS=5
      - WAITFOR=namenode:8020

  # gatewayserver:
  #   image: linuxserver/openssh-server
  #   hostname: gatewayserver
  #   restart: unless-stopped
  #   ports:
  #     - 22222:2222
  #   networks:
  #     - hadoopnet
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=UTC
  #     - USER_NAME=hadoop
  #     - USER_PASSWORD=hadoop
  #     - PASSWORD_ACCESS=true
  #   volumes:
  #     - ./gatewayserver__sshd_config:/etc/ssh/sshd_config:ro
